understanding the dataset to explore how the data is present in the database and if there is a need of creating some aggregated tables that can help with:

. vendor selection for profitablity

. product pricing optimization

In [12]:
import pandas as pd
import sqlite3

In [13]:
#creating database connection
conn = sqlite3.connect('inventory.db')

In [14]:
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type = 'table'",conn)
tables

              name
0  begin_inventory
1    end_inventory
2        purchases
3  purchase_prices
4            sales
5   vendor_invoice

In [17]:
pd.read_sql("select count(*) from purchases", conn)

   count(*)
0   2372474

In [21]:
for table in tables['name']:
    print('-'*50,f'{table}','-'*50)
    print('count of records: ', pd.read_sql(f'select count(*) as count from {table}',conn)['count'].values[0])
    display(pd.read_)

-------------------------------------------------- begin_inventory --------------------------------------------------
count of records:  206529
-------------------------------------------------- end_inventory --------------------------------------------------
count of records:  224489
-------------------------------------------------- purchases --------------------------------------------------
count of records:  2372474
-------------------------------------------------- purchase_prices --------------------------------------------------
count of records:  12261
-------------------------------------------------- sales --------------------------------------------------
count of records:  12825363
-------------------------------------------------- vendor_invoice --------------------------------------------------
count of records:  5543